spring.application.name=proxy
server.port=8000
monolith.url=${MONOLITH_URL:http://localhost:8080}
movies.service.url=${MOVIES_SERVICE_URL:http://localhost:8081}
gradual.migration=${GRADUAL_MIGRATION:true}
movies.migration.percent=${MOVIES_MIGRATION_PERCENT:100}