apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaHJjLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJiV2xyYUdWc01UazRORHBuYVhSb2RXSmZjR0YwWHpFeFFVVXpVMVZUVVRCT2MydDVOV2Q1Wm1KRWVrRmZiazVUZDFKd1YxVnVRMGQ2T1V4dFIzUTJVMGx4U1VObU9YUkZZMVZ6UzJjeWFWZFljWEZsZVc5VVZFSkdTRkpOTjA1TVMxVkZiamxvWkZJPSIKICAgICAgICB9CiAgICB9Cn0K
type: kubernetes.io/dockerconfigjson
