@startuml CinemaAbyss_container

title CinemaAbyss system containers

'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
!include <C4/C4_Component.puml>

' Users
Person(user, "User", "A user of the service")

' CinemaAbyss system
Container_Boundary(CinAbSystem, "CinemaAbyss system") {
    Container(PaymentService, "Payment processing", "Provide payment functions")
    Container(CinemaService, "Cinema service", "Movies management")



}

' External systems
System_Ext(PaymentSystem, "Payment system", "Process transactions")
System_Ext(RecommendationSystem, "Recommendation system", "Generate recommendations")
System_Ext(Cinemas, "Cinemas", "Provide content")
'System_Ext(FileService, "S3", "Store files")

' Relations
Rel(PaymentService, PaymentSystem, "")
Rel(CinemaService, Cinemas, "")



@enduml